---

- name: check the Centos release
  fail: msg="version of Centos should be 8+"
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version|int < 8

- name: config sysctl
  copy:
    src: buildkitd.toml
    dest: $HOME/buildkitd.toml
    owner: root
    group: root
    mode: '0644'

- name: install simulator
  shell: docker run --privileged --rm tonistiigi/binfmt --install all

- name: create builder and use it
  shell: docker buildx create --use --name mybuilder --config=$HOME/buildkitd.toml
