---

- name: restart docker
  service: name=docker state=restarted

- name: reload docker
  service: name=docker state=reloaded

- name: yum-clean-metadata
  command: yum clean metadata
  args:
    warn: no
