---

- name: disable docker service
  service:
    name: docker
    state: stopped
    enabled: no

- name: uninstall dependencies
  yum:
    name: [
      'docker-ce',
      'docker-ce-cli',
      'docker-scan-plugin',
      'containerd.io',
      'yum-utils',
      'device-mapper-persistent-data',
      'lvm2'
    ]
    state: absent

- name: remove docker-ce repo (and clean up left-over metadata)
  yum_repository:
    name: docker-ce
    state: absent
  notify: yum-clean-metadata

- name: remove k8s.conf
  file:
    path: /etc/sysctl.d/k8s.conf
    state: absent

- name: remove daemon.json
  file:
    path: /etc/docker/daemon.json
    state: absent

- name: remove folder for docker
  file:
    path: /var/lib/docker
    state: absent

- name: remove folder for containerd
  file:
    path: /var/lib/containerd
    state: absent

- name: remove folders or files left
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/sysctl.d/k8s.conf
    - /etc/docker/daemon.json
    - /var/lib/docker
    - /var/lib/containerd
